default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# format pyproject.toml file
- repo: https://github.com/kieran-ryan/pyprojectsort
  rev: v0.4.0
  hooks:
    - id: pyprojectsort
# export python requirements
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.9.11
  hooks:
    - id: uv-export
      args: ["--output-file", "requirements.txt", "--no-dev", "--locked", "--quiet"]
    - id: uv-export
      args: ["--output-file", "requirements.dev.txt", "--only-dev", "--locked", "--quiet"]
